// Verified organization names and official domains. Impact metrics are intentionally
// omitted: ShareCompass should never present invented charity performance data.
const org = (id, name, handle, loc, country, cause, types, urgent = false) => ({
  id, real: true, name, handle, website: `https://${handle}`, loc,
  region: "global", country, cause, urgent, types, following: 0,
  need: urgent ? 82 : 55, image: null,
  blurb: `Explore ${name}'s current ${cause.toLowerCase()} programs, ways to volunteer, and verified giving options on its official website.`,
});

export const EXTRA_ORGS = [
  org(101, "CARE", "care.org", "Global", "US", "Disaster", ["Money", "Time"], true),
  org(102, "Mercy Corps", "mercycorps.org", "Global", "US", "Disaster", ["Money", "Time"], true),
  org(103, "International Medical Corps", "internationalmedicalcorps.org", "Global", "US", "Health", ["Money", "Time"], true),
  org(104, "Partners In Health", "pih.org", "Global", "US", "Health", ["Money", "Time"]),
  org(105, "Project HOPE", "projecthope.org", "Global", "US", "Health", ["Money", "Time"], true),
  org(106, "PATH", "path.org", "Global", "US", "Health", ["Money", "Time"]),
  org(107, "Helen Keller Intl", "helenkellerintl.org", "Global", "US", "Health", ["Money"]),
  org(108, "Operation Smile", "operationsmile.org", "Global", "US", "Health", ["Money", "Time"]),
  org(109, "The Fred Hollows Foundation", "hollows.org", "Global", "AU", "Health", ["Money"]),
  org(110, "Sightsavers", "sightsavers.org", "Global", "GB", "Health", ["Money"]),
  org(111, "WaterAid", "wateraid.org", "Global", "GB", "Water", ["Money", "Time"]),
  org(112, "Water.org", "water.org", "Global", "US", "Water", ["Money"]),
  org(113, "The Water Project", "thewaterproject.org", "Sub-Saharan Africa", "US", "Water", ["Money"]),
  org(114, "DigDeep", "digdeep.org", "United States", "US", "Water", ["Money", "Time"]),
  org(115, "Action Against Hunger", "actionagainsthunger.org", "Global", "US", "Hunger", ["Money", "Time"], true),
  org(116, "The Hunger Project", "thp.org", "Global", "US", "Hunger", ["Money", "Time"]),
  org(117, "No Kid Hungry", "nokidhungry.org", "United States", "US", "Hunger", ["Money", "Time"]),
  org(118, "Food Bank For New York City", "foodbanknyc.org", "New York, USA", "US", "Hunger", ["Money", "Time", "Goods"]),
  org(119, "Atlanta Community Food Bank", "acfb.org", "Georgia, USA", "US", "Hunger", ["Money", "Time", "Goods"]),
  org(120, "FareShare", "fareshare.org.uk", "United Kingdom", "GB", "Hunger", ["Money", "Time", "Goods"]),
  org(121, "ShelterBox", "shelterbox.org", "Global", "GB", "Housing", ["Money", "Time"], true),
  org(122, "New Story", "newstorycharity.org", "Latin America", "US", "Housing", ["Money"]),
  org(123, "One Acre Fund", "oneacrefund.org", "Sub-Saharan Africa", "KE", "Hunger", ["Money", "Time"]),
  org(124, "Heifer International", "heifer.org", "Global", "US", "Hunger", ["Money", "Sponsor"]),
  org(125, "Room to Read", "roomtoread.org", "Global", "US", "Education", ["Money", "Time"]),
  org(126, "Pratham", "pratham.org", "India", "IN", "Education", ["Money", "Time"]),
  org(127, "Teach For All", "teachforall.org", "Global", "US", "Education", ["Money", "Time"]),
  org(128, "Camfed", "camfed.org", "Sub-Saharan Africa", "GB", "Education", ["Money", "Sponsor"]),
  org(129, "Pencils of Promise", "pencilsofpromise.org", "Global", "US", "Education", ["Money", "Time"]),
  org(130, "Khan Academy", "khanacademy.org", "Global", "US", "Education", ["Money", "Time"]),
  org(131, "Code.org", "code.org", "Global", "US", "Education", ["Money", "Time"]),
  org(132, "Girls Who Code", "girlswhocode.com", "Global", "US", "Education", ["Money", "Time"]),
  org(133, "Malala Fund", "malala.org", "Global", "US", "Education", ["Money"]),
  org(134, "Plan International", "plan-international.org", "Global", "GB", "Children", ["Money", "Sponsor"]),
  org(135, "World Vision", "worldvision.org", "Global", "US", "Children", ["Money", "Sponsor"], true),
  org(136, "SOS Children's Villages", "sos-childrensvillages.org", "Global", "AT", "Children", ["Money", "Sponsor"]),
  org(137, "St. Jude Children's Research Hospital", "stjude.org", "United States", "US", "Children", ["Money", "Time"]),
  org(138, "Make-A-Wish", "wish.org", "Global", "US", "Children", ["Money", "Time"]),
  org(139, "Ronald McDonald House Charities", "rmhc.org", "Global", "US", "Children", ["Money", "Time"]),
  org(140, "ChildFund International", "childfund.org", "Global", "US", "Children", ["Money", "Sponsor"]),
  org(141, "War Child", "warchild.org.uk", "Global", "GB", "Children", ["Money", "Time"], true),
  org(142, "UNHCR", "unhcr.org", "Global", "CH", "Refugees", ["Money", "Time"], true),
  org(143, "Refugees International", "refugeesinternational.org", "Global", "US", "Refugees", ["Money"]),
  org(144, "RefugePoint", "refugepoint.org", "Global", "US", "Refugees", ["Money", "Time"]),
  org(145, "HIAS", "hias.org", "Global", "US", "Refugees", ["Money", "Time"], true),
  org(146, "Choose Love", "chooselove.org", "Global", "GB", "Refugees", ["Money", "Goods"], true),
  org(147, "Norwegian Refugee Council", "nrc.no", "Global", "NO", "Refugees", ["Money", "Time"], true),
  org(148, "Danish Refugee Council", "drc.ngo", "Global", "DK", "Refugees", ["Money", "Time"], true),
  org(149, "Catholic Relief Services", "crs.org", "Global", "US", "Disaster", ["Money", "Time"], true),
  org(150, "Islamic Relief Worldwide", "islamic-relief.org", "Global", "GB", "Disaster", ["Money", "Time"], true),
  org(151, "Red Cross", "ifrc.org", "Global", "CH", "Disaster", ["Money", "Time", "Goods"], true),
  org(152, "Team Rubicon", "teamrubiconusa.org", "United States", "US", "Disaster", ["Money", "Time"], true),
  org(153, "All Hands and Hearts", "allhandsandhearts.org", "Global", "US", "Disaster", ["Money", "Time"], true),
  org(154, "GlobalGiving", "globalgiving.org", "Global", "US", "Disaster", ["Money"], true),
  org(155, "Akshaya Patra", "akshayapatra.org", "India", "IN", "Hunger", ["Money", "Time"]),
  org(156, "The Trussell Trust", "trussell.org.uk", "United Kingdom", "GB", "Hunger", ["Money", "Time", "Goods"]),
  org(157, "Covenant House", "covenanthouse.org", "North America", "US", "Housing", ["Money", "Time", "Goods"]),
  org(158, "Depaul International", "int.depaulcharity.org", "Global", "GB", "Housing", ["Money", "Time"]),
  org(159, "Build Change", "buildchange.org", "Global", "US", "Housing", ["Money", "Time"]),
  org(160, "Barefoot College International", "barefootcollege.org", "Global", "IN", "Education", ["Money", "Time"]),
  org(161, "African Library Project", "africanlibraryproject.org", "Africa", "US", "Education", ["Money", "Time", "Goods"]),
  org(162, "Books For Africa", "booksforafrica.org", "Africa", "US", "Education", ["Money", "Time", "Goods"]),
  org(163, "Amref Health Africa", "amref.org", "Africa", "KE", "Health", ["Money", "Time"]),
  org(164, "Last Mile Health", "lastmilehealth.org", "Africa", "US", "Health", ["Money", "Time"]),
  org(165, "mothers2mothers", "m2m.org", "Africa", "ZA", "Health", ["Money", "Time"]),
  org(166, "GiveDirectly", "givedirectly.org", "Global", "US", "Disaster", ["Money"], true),
];
